// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw1-hangman/internal/domain/entities"
)

// NewMockWordsRepository creates a new instance of MockWordsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWordsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWordsRepository {
	mock := &MockWordsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWordsRepository is an autogenerated mock type for the WordsRepository type
type MockWordsRepository struct {
	mock.Mock
}

type MockWordsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWordsRepository) EXPECT() *MockWordsRepository_Expecter {
	return &MockWordsRepository_Expecter{mock: &_m.Mock}
}

// RandomWord provides a mock function for the type MockWordsRepository
func (_mock *MockWordsRepository) RandomWord(level entities.Level, category entities.Category) (entities.Word, error) {
	ret := _mock.Called(level, category)

	if len(ret) == 0 {
		panic("no return value specified for RandomWord")
	}

	var r0 entities.Word
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.Level, entities.Category) (entities.Word, error)); ok {
		return returnFunc(level, category)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.Level, entities.Category) entities.Word); ok {
		r0 = returnFunc(level, category)
	} else {
		r0 = ret.Get(0).(entities.Word)
	}
	if returnFunc, ok := ret.Get(1).(func(entities.Level, entities.Category) error); ok {
		r1 = returnFunc(level, category)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWordsRepository_RandomWord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RandomWord'
type MockWordsRepository_RandomWord_Call struct {
	*mock.Call
}

// RandomWord is a helper method to define mock.On call
//   - level entities.Level
//   - category entities.Category
func (_e *MockWordsRepository_Expecter) RandomWord(level interface{}, category interface{}) *MockWordsRepository_RandomWord_Call {
	return &MockWordsRepository_RandomWord_Call{Call: _e.mock.On("RandomWord", level, category)}
}

func (_c *MockWordsRepository_RandomWord_Call) Run(run func(level entities.Level, category entities.Category)) *MockWordsRepository_RandomWord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Level
		if args[0] != nil {
			arg0 = args[0].(entities.Level)
		}
		var arg1 entities.Category
		if args[1] != nil {
			arg1 = args[1].(entities.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWordsRepository_RandomWord_Call) Return(word entities.Word, err error) *MockWordsRepository_RandomWord_Call {
	_c.Call.Return(word, err)
	return _c
}

func (_c *MockWordsRepository_RandomWord_Call) RunAndReturn(run func(level entities.Level, category entities.Category) (entities.Word, error)) *MockWordsRepository_RandomWord_Call {
	_c.Call.Return(run)
	return _c
}
