// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRandomSelector creates a new instance of MockRandomSelector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRandomSelector[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRandomSelector[T] {
	mock := &MockRandomSelector[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRandomSelector is an autogenerated mock type for the RandomSelector type
type MockRandomSelector[T any] struct {
	mock.Mock
}

type MockRandomSelector_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockRandomSelector[T]) EXPECT() *MockRandomSelector_Expecter[T] {
	return &MockRandomSelector_Expecter[T]{mock: &_m.Mock}
}

// Choose provides a mock function for the type MockRandomSelector
func (_mock *MockRandomSelector[T]) Choose(items []T) T {
	ret := _mock.Called(items)

	if len(ret) == 0 {
		panic("no return value specified for Choose")
	}

	var r0 T
	if returnFunc, ok := ret.Get(0).(func([]T) T); ok {
		r0 = returnFunc(items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	return r0
}

// MockRandomSelector_Choose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Choose'
type MockRandomSelector_Choose_Call[T any] struct {
	*mock.Call
}

// Choose is a helper method to define mock.On call
//   - items []T
func (_e *MockRandomSelector_Expecter[T]) Choose(items interface{}) *MockRandomSelector_Choose_Call[T] {
	return &MockRandomSelector_Choose_Call[T]{Call: _e.mock.On("Choose", items)}
}

func (_c *MockRandomSelector_Choose_Call[T]) Run(run func(items []T)) *MockRandomSelector_Choose_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []T
		if args[0] != nil {
			arg0 = args[0].([]T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRandomSelector_Choose_Call[T]) Return(v T) *MockRandomSelector_Choose_Call[T] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockRandomSelector_Choose_Call[T]) RunAndReturn(run func(items []T) T) *MockRandomSelector_Choose_Call[T] {
	_c.Call.Return(run)
	return _c
}
