// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw1-hangman/internal/domain/entities"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// Category provides a mock function for the type MockConfig
func (_mock *MockConfig) Category() entities.Category {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Category")
	}

	var r0 entities.Category
	if returnFunc, ok := ret.Get(0).(func() entities.Category); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(entities.Category)
	}
	return r0
}

// MockConfig_Category_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Category'
type MockConfig_Category_Call struct {
	*mock.Call
}

// Category is a helper method to define mock.On call
func (_e *MockConfig_Expecter) Category() *MockConfig_Category_Call {
	return &MockConfig_Category_Call{Call: _e.mock.On("Category")}
}

func (_c *MockConfig_Category_Call) Run(run func()) *MockConfig_Category_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_Category_Call) Return(category entities.Category) *MockConfig_Category_Call {
	_c.Call.Return(category)
	return _c
}

func (_c *MockConfig_Category_Call) RunAndReturn(run func() entities.Category) *MockConfig_Category_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateWord provides a mock function for the type MockConfig
func (_mock *MockConfig) GenerateWord() (entities.Word, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateWord")
	}

	var r0 entities.Word
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (entities.Word, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() entities.Word); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(entities.Word)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfig_GenerateWord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateWord'
type MockConfig_GenerateWord_Call struct {
	*mock.Call
}

// GenerateWord is a helper method to define mock.On call
func (_e *MockConfig_Expecter) GenerateWord() *MockConfig_GenerateWord_Call {
	return &MockConfig_GenerateWord_Call{Call: _e.mock.On("GenerateWord")}
}

func (_c *MockConfig_GenerateWord_Call) Run(run func()) *MockConfig_GenerateWord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_GenerateWord_Call) Return(word entities.Word, err error) *MockConfig_GenerateWord_Call {
	_c.Call.Return(word, err)
	return _c
}

func (_c *MockConfig_GenerateWord_Call) RunAndReturn(run func() (entities.Word, error)) *MockConfig_GenerateWord_Call {
	_c.Call.Return(run)
	return _c
}

// Level provides a mock function for the type MockConfig
func (_mock *MockConfig) Level() entities.Level {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Level")
	}

	var r0 entities.Level
	if returnFunc, ok := ret.Get(0).(func() entities.Level); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(entities.Level)
	}
	return r0
}

// MockConfig_Level_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Level'
type MockConfig_Level_Call struct {
	*mock.Call
}

// Level is a helper method to define mock.On call
func (_e *MockConfig_Expecter) Level() *MockConfig_Level_Call {
	return &MockConfig_Level_Call{Call: _e.mock.On("Level")}
}

func (_c *MockConfig_Level_Call) Run(run func()) *MockConfig_Level_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_Level_Call) Return(level entities.Level) *MockConfig_Level_Call {
	_c.Call.Return(level)
	return _c
}

func (_c *MockConfig_Level_Call) RunAndReturn(run func() entities.Level) *MockConfig_Level_Call {
	_c.Call.Return(run)
	return _c
}

// SetCategory provides a mock function for the type MockConfig
func (_mock *MockConfig) SetCategory(category entities.Category) {
	_mock.Called(category)
	return
}

// MockConfig_SetCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCategory'
type MockConfig_SetCategory_Call struct {
	*mock.Call
}

// SetCategory is a helper method to define mock.On call
//   - category entities.Category
func (_e *MockConfig_Expecter) SetCategory(category interface{}) *MockConfig_SetCategory_Call {
	return &MockConfig_SetCategory_Call{Call: _e.mock.On("SetCategory", category)}
}

func (_c *MockConfig_SetCategory_Call) Run(run func(category entities.Category)) *MockConfig_SetCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Category
		if args[0] != nil {
			arg0 = args[0].(entities.Category)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_SetCategory_Call) Return() *MockConfig_SetCategory_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfig_SetCategory_Call) RunAndReturn(run func(category entities.Category)) *MockConfig_SetCategory_Call {
	_c.Run(run)
	return _c
}

// SetLevel provides a mock function for the type MockConfig
func (_mock *MockConfig) SetLevel(level entities.Level) {
	_mock.Called(level)
	return
}

// MockConfig_SetLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLevel'
type MockConfig_SetLevel_Call struct {
	*mock.Call
}

// SetLevel is a helper method to define mock.On call
//   - level entities.Level
func (_e *MockConfig_Expecter) SetLevel(level interface{}) *MockConfig_SetLevel_Call {
	return &MockConfig_SetLevel_Call{Call: _e.mock.On("SetLevel", level)}
}

func (_c *MockConfig_SetLevel_Call) Run(run func(level entities.Level)) *MockConfig_SetLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Level
		if args[0] != nil {
			arg0 = args[0].(entities.Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfig_SetLevel_Call) Return() *MockConfig_SetLevel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfig_SetLevel_Call) RunAndReturn(run func(level entities.Level)) *MockConfig_SetLevel_Call {
	_c.Run(run)
	return _c
}
