// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw1-hangman/internal/domain/entities"
)

// NewMockGame creates a new instance of MockGame. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGame(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGame {
	mock := &MockGame{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGame is an autogenerated mock type for the Game type
type MockGame struct {
	mock.Mock
}

type MockGame_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGame) EXPECT() *MockGame_Expecter {
	return &MockGame_Expecter{mock: &_m.Mock}
}

// GuessLetter provides a mock function for the type MockGame
func (_mock *MockGame) GuessLetter(r rune) bool {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GuessLetter")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(rune) bool); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGame_GuessLetter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GuessLetter'
type MockGame_GuessLetter_Call struct {
	*mock.Call
}

// GuessLetter is a helper method to define mock.On call
//   - r rune
func (_e *MockGame_Expecter) GuessLetter(r interface{}) *MockGame_GuessLetter_Call {
	return &MockGame_GuessLetter_Call{Call: _e.mock.On("GuessLetter", r)}
}

func (_c *MockGame_GuessLetter_Call) Run(run func(r rune)) *MockGame_GuessLetter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 rune
		if args[0] != nil {
			arg0 = args[0].(rune)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGame_GuessLetter_Call) Return(b bool) *MockGame_GuessLetter_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGame_GuessLetter_Call) RunAndReturn(run func(r rune) bool) *MockGame_GuessLetter_Call {
	_c.Call.Return(run)
	return _c
}

// GuessedLetters provides a mock function for the type MockGame
func (_mock *MockGame) GuessedLetters() []rune {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GuessedLetters")
	}

	var r0 []rune
	if returnFunc, ok := ret.Get(0).(func() []rune); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rune)
		}
	}
	return r0
}

// MockGame_GuessedLetters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GuessedLetters'
type MockGame_GuessedLetters_Call struct {
	*mock.Call
}

// GuessedLetters is a helper method to define mock.On call
func (_e *MockGame_Expecter) GuessedLetters() *MockGame_GuessedLetters_Call {
	return &MockGame_GuessedLetters_Call{Call: _e.mock.On("GuessedLetters")}
}

func (_c *MockGame_GuessedLetters_Call) Run(run func()) *MockGame_GuessedLetters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGame_GuessedLetters_Call) Return(runes []rune) *MockGame_GuessedLetters_Call {
	_c.Call.Return(runes)
	return _c
}

func (_c *MockGame_GuessedLetters_Call) RunAndReturn(run func() []rune) *MockGame_GuessedLetters_Call {
	_c.Call.Return(run)
	return _c
}

// InProgress provides a mock function for the type MockGame
func (_mock *MockGame) InProgress() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InProgress")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGame_InProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InProgress'
type MockGame_InProgress_Call struct {
	*mock.Call
}

// InProgress is a helper method to define mock.On call
func (_e *MockGame_Expecter) InProgress() *MockGame_InProgress_Call {
	return &MockGame_InProgress_Call{Call: _e.mock.On("InProgress")}
}

func (_c *MockGame_InProgress_Call) Run(run func()) *MockGame_InProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGame_InProgress_Call) Return(b bool) *MockGame_InProgress_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGame_InProgress_Call) RunAndReturn(run func() bool) *MockGame_InProgress_Call {
	_c.Call.Return(run)
	return _c
}

// IsLetterGuessed provides a mock function for the type MockGame
func (_mock *MockGame) IsLetterGuessed(r rune) bool {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for IsLetterGuessed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(rune) bool); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGame_IsLetterGuessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLetterGuessed'
type MockGame_IsLetterGuessed_Call struct {
	*mock.Call
}

// IsLetterGuessed is a helper method to define mock.On call
//   - r rune
func (_e *MockGame_Expecter) IsLetterGuessed(r interface{}) *MockGame_IsLetterGuessed_Call {
	return &MockGame_IsLetterGuessed_Call{Call: _e.mock.On("IsLetterGuessed", r)}
}

func (_c *MockGame_IsLetterGuessed_Call) Run(run func(r rune)) *MockGame_IsLetterGuessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 rune
		if args[0] != nil {
			arg0 = args[0].(rune)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGame_IsLetterGuessed_Call) Return(b bool) *MockGame_IsLetterGuessed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGame_IsLetterGuessed_Call) RunAndReturn(run func(r rune) bool) *MockGame_IsLetterGuessed_Call {
	_c.Call.Return(run)
	return _c
}

// IsWon provides a mock function for the type MockGame
func (_mock *MockGame) IsWon() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsWon")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockGame_IsWon_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWon'
type MockGame_IsWon_Call struct {
	*mock.Call
}

// IsWon is a helper method to define mock.On call
func (_e *MockGame_Expecter) IsWon() *MockGame_IsWon_Call {
	return &MockGame_IsWon_Call{Call: _e.mock.On("IsWon")}
}

func (_c *MockGame_IsWon_Call) Run(run func()) *MockGame_IsWon_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGame_IsWon_Call) Return(b bool) *MockGame_IsWon_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockGame_IsWon_Call) RunAndReturn(run func() bool) *MockGame_IsWon_Call {
	_c.Call.Return(run)
	return _c
}

// RemainingAttempts provides a mock function for the type MockGame
func (_mock *MockGame) RemainingAttempts() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemainingAttempts")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockGame_RemainingAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemainingAttempts'
type MockGame_RemainingAttempts_Call struct {
	*mock.Call
}

// RemainingAttempts is a helper method to define mock.On call
func (_e *MockGame_Expecter) RemainingAttempts() *MockGame_RemainingAttempts_Call {
	return &MockGame_RemainingAttempts_Call{Call: _e.mock.On("RemainingAttempts")}
}

func (_c *MockGame_RemainingAttempts_Call) Run(run func()) *MockGame_RemainingAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGame_RemainingAttempts_Call) Return(n int) *MockGame_RemainingAttempts_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockGame_RemainingAttempts_Call) RunAndReturn(run func() int) *MockGame_RemainingAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// Word provides a mock function for the type MockGame
func (_mock *MockGame) Word() entities.Word {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Word")
	}

	var r0 entities.Word
	if returnFunc, ok := ret.Get(0).(func() entities.Word); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(entities.Word)
	}
	return r0
}

// MockGame_Word_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Word'
type MockGame_Word_Call struct {
	*mock.Call
}

// Word is a helper method to define mock.On call
func (_e *MockGame_Expecter) Word() *MockGame_Word_Call {
	return &MockGame_Word_Call{Call: _e.mock.On("Word")}
}

func (_c *MockGame_Word_Call) Run(run func()) *MockGame_Word_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGame_Word_Call) Return(word entities.Word) *MockGame_Word_Call {
	_c.Call.Return(word)
	return _c
}

func (_c *MockGame_Word_Call) RunAndReturn(run func() entities.Word) *MockGame_Word_Call {
	_c.Call.Return(run)
	return _c
}

// WordMask provides a mock function for the type MockGame
func (_mock *MockGame) WordMask() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WordMask")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGame_WordMask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WordMask'
type MockGame_WordMask_Call struct {
	*mock.Call
}

// WordMask is a helper method to define mock.On call
func (_e *MockGame_Expecter) WordMask() *MockGame_WordMask_Call {
	return &MockGame_WordMask_Call{Call: _e.mock.On("WordMask")}
}

func (_c *MockGame_WordMask_Call) Run(run func()) *MockGame_WordMask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGame_WordMask_Call) Return(s string) *MockGame_WordMask_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGame_WordMask_Call) RunAndReturn(run func() string) *MockGame_WordMask_Call {
	_c.Call.Return(run)
	return _c
}
